// components/Timeline.vue
<template lang="pug">
  .timeline
    div(v-for="(element, index) in elements")
      timeline-event(:element="element")
</template>

<script lang="ts">
import Vue, { PropType } from 'vue';
import TimelineEvent from './TimelineEvent.vue';
import TimelineElement from '../src/TimelineElement';

export default Vue.extend({
  name: 'Timeline',
  components: {
    TimelineEvent,
  },
  props: {
    elements: {
      type: Array as PropType<Array<TimelineElement>>,
      required: true,
    },
  },
});
</script>

<style lang="postcss" scoped>
.timeline {
  @apply p-4;
  @apply h-auto;
  @apply relative;
}

.timeline::before {
  content: "";
  @apply w-1;
  @apply h-full;
  @apply block;
  @apply absolute;
  @apply bg-gray-600;
  @apply left-11;
  @apply top-11;
}

.timeline > *:last-child::before {
  content: "";
  @apply block;
  @apply absolute;
  @apply bg-white;
  @apply w-1;
  @apply h-48;
  @apply left-11;
  @apply -bottom-20;
}
</style>

// frontend/src/lib/timeline/Timeline.svelte
<script lang="ts">
  import type { SvelteComponentTyped } from "svelte";
  
  export let elements: any[];
  export let component: typeof SvelteComponentTyped<{ element: any }>;
</script>

<ol class="relative">
  {#each elements as element }
    <li class="timeline-item">
      <div class="relative pb-6">
        <div class="line">
          <svelte:component this={component} element={element} />
        </div>
      </div>
    </li>
  {/each}
</ol>

<style>
  .timeline-item {
    @apply pl-8;
  }

  .timeline-item::before {
    content: "";
    @apply block absolute w-2 h-2 left-2 mt-2.5 rounded-full bg-gray-700 z-50;
  }

  .timeline-item:not(:last-child) .line::before {
    content: "";
    @apply block absolute w-1 h-full -left-[22px] top-3 rounded-full bg-gray-400;
  }
</style>
